project:
  type: website
  output-dir: docs
website:
  title: "Piyush Chaudhari"
  favicon: photos/Piyush.png
  twitter-card:
    creator: "@iampiyushvc"
  navbar:
    right:
      - text: "Piyush"
        href: index.qmd
      - text: "Profile"
        href: about.qmd
  page-footer: 
    background: "#D6DBDF"
    right: 
      - icon: twitter
        href: https://twitter.com/iampiyushvc 
      - icon: instagram
        href: https://www.instagram.com/iampiyushvc
    left: "This website was build using [Quarto](https://quarto.org/). 2024 Piyush Chaudhari"
format:
  html:
    theme: 
      - _variables.scss
      #light: yeti
      #dark: darkly
    #css: styles.css
    toc: true
    page-layout: full

editor: visual