project:
  type: website
  output-dir: docs
  
execute: 
  freeze: auto

website:
  title: "Piyush Chaudhari"
  favicon: photos/Piyush.png
  twitter-card:
     creator: "@iampiyushvc"
  navbar: 
    #background: black
    right:
      - href: index.qmd
        text: Piyush
      - href: about.qmd
        text: Profile
      
  #page-footer:
    #background: black
    #left: "© Copyright 2023 Piyush Chaudhari. Except where otherwise noted, all text and images licensed CC-BY-NC 4.0."
  page-footer: 
    background: "#D6DBDF"
    right: 
      - icon: twitter
        href: https://twitter.com/iampiyushvc 
      - icon: instagram
        href: https://www.instagram.com/iampiyushvc
     
    left: "This website was build using [Quarto](https://quarto.org/). 2023 Piyush Chaudhari"
format:
  html:
    theme: 
      - _variables.scss
      #light: yeti
      #dark: darkly
    #css: styles.css
    toc: true
    page-layout: full

editor: visual

