<!DOCTYPE html>
<html lang="en"><head>
<link href="../../../photos/Piyush.png" rel="icon" type="image/png">
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-dark-f418161beb48e0141c760e455f12af2c.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.36">

  <meta name="author" content="Piyush Chaudhari">
  <title>Piyush Chaudhari – Reflexion: Language Agents with Verbal Reinforcement Learning</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/theme/quarto-fdc93494f2580a7e050003a96af38920.css">
  <link href="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta name="twitter:title" content="Reflexion: Language Agents with Verbal Reinforcement Learning – Piyush Chaudhari">
<meta name="twitter:creator" content="@iampiyushvc">
<meta name="twitter:card" content="summary">
</head>
<body class="quarto-dark">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Reflexion: Language Agents with Verbal Reinforcement Learning</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Piyush Chaudhari 
</div>
</div>
</div>

</section>
<section class="slide level2">

<h3 id="current-problem">Current Problem</h3>
<div style="font-size: 80%;">
<p>Recent works demonstrate that LLMs can act as autonomous agents:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>System</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ReAct</td>
<td>Reason + Act in text-based environments</td>
</tr>
<tr class="even">
<td>SayCan</td>
<td>Grounding language in robotic affordances</td>
</tr>
<tr class="odd">
<td>Toolformer</td>
<td>LLMs that teach themselves to use API tools</td>
</tr>
<tr class="even">
<td>WebGPT</td>
<td>Browser-assisted Q&amp;A with human feedback</td>
</tr>
<tr class="odd">
<td>HuggingGPT</td>
<td>Coordinating AI models via ChatGPT</td>
</tr>
<tr class="even">
<td>Generative Agents</td>
<td>Simulating believable human behaviour</td>
</tr>
</tbody>
</table>
<p>All of these rely on <strong>in-context few-shot examples</strong> as the only form of teaching — because traditional RL requires weight updates the agents cannot do at inference time.</p>
</div>
</section>
<section class="slide level2">

<h3 id="issue-with-traditional-reinforcement-learning">Issue with Traditional Reinforcement Learning</h3>
<div style="font-size: 55%;">
<p><strong>Traditional RL requires:</strong></p>
<ul>
<li>Millions of environment interactions</li>
<li>Expensive gradient-based fine-tuning</li>
<li>Massive compute budgets</li>
<li>Retraining for each new task</li>
</ul>
<p><strong>What LLM agents have today:</strong></p>
<ul>
<li>In-context few-shot examples only</li>
<li>No weight updates at inference</li>
<li>No persistent learning across episodes</li>
<li>Frozen model parameters</li>
</ul>
<blockquote>
<p><strong>The Gap:</strong> LLM agents can <em>observe</em> that they failed — but they cannot update their parameters. Without a mechanism to convert failure signals into actionable learning, every episode starts from scratch.</p>
</blockquote>
</div>
</section>
<section class="slide level2">

<h3 id="approach">Approach</h3>
<!-- ![](images/x1.png){.absolute .fragment bottom="10" right="10" width="650"} -->
<div style="font-size: 75%;">
<p>Reflexion draws inspiration from human <strong>metacognitive learning</strong>:</p>
<p><span class="math display">\[
ATTEMPT → FAIL → REFLECT → STORE → RETRY
\]</span></p>
<ol type="1">
<li><strong>ATTEMPT</strong> — Try the task with current knowledge</li>
<li><strong>FAIL</strong> — Receive feedback (binary, scalar, or free-form)</li>
<li><strong>REFLECT</strong> — Identify <em>why</em> the attempt failed (credit assignment)</li>
<li><strong>STORE</strong> — Record key insight in long-term memory</li>
<li><strong>RETRY</strong> — Apply lessons in the next attempt</li>
</ol>
<blockquote>
<p><strong>Reflexion Formalises This Loop:</strong> Instead of updating neural weights, Reflexion converts feedback into <strong>verbal summaries</strong> stored in an episodic memory buffer — acting as a <em>semantic gradient</em> that guides the next attempt.</p>
</blockquote>
</div>
</section>
<section class="slide level2">

<h3 id="reflexion-core-concept">Reflexion : Core Concept</h3>
<div style="font-size: 55%;">
<blockquote>
<p>Reflexion reinforces language agents <strong>not by updating weights</strong>, but by converting feedback into verbal language stored in memory, used to guide better decisions in future trials.</p>
</blockquote>
<p><strong>Six key advantages:</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 55%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>Property</th>
<th>Detail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Lightweight</td>
<td>No fine-tuning or gradient descent — works with any frozen LLM</td>
</tr>
<tr class="even">
<td>Nuanced Feedback</td>
<td>Verbal explanations carry more information than scalar rewards</td>
</tr>
<tr class="odd">
<td>Interpretable</td>
<td>Self-reflections can be inspected, audited, or monitored</td>
</tr>
<tr class="even">
<td>Flexible</td>
<td>Works with binary, scalar, or free-form feedback from any source</td>
</tr>
<tr class="odd">
<td>Few-shot Learning</td>
<td>Strong improvements within just a handful of trials</td>
</tr>
<tr class="even">
<td>Language Agnostic</td>
<td>Demonstrated on Python AND Rust code generation tasks</td>
</tr>
</tbody>
</table>
</div>
</section>
<section class="slide level2">

<h3 id="redefining-the-policy">Redefining the Policy</h3>
<div style="font-size: 75%;">
<p><strong>Traditional RL policy:</strong></p>
<p><span class="math display">\[\pi_\theta(a_t \mid s_t), \quad \theta = \text{model weights}\]</span></p>
<p><strong>Reflexion policy:</strong></p>
<p><span class="math display">\[\pi_\theta(a_t \mid s_t), \quad \theta = \{M_a,\ \textit{mem}\}\]</span></p>
<p>Where:</p>
<ul>
<li><strong><span class="math inline">\(M_a\)</span></strong> = the Actor LLM (frozen weights)</li>
<li><strong><span class="math inline">\(\textit{mem}\)</span></strong> = episodic memory buffer of self-reflections</li>
</ul>
<blockquote>
<p><strong>Key Insight:</strong> By adding <code>mem</code> as a second policy parameter, Reflexion “optimises” agent behaviour through verbal learning — without ever touching LLM weights. The self-reflection text acts as a <strong>semantic gradient signal</strong>.</p>
</blockquote>
</div>
</section>
<section class="slide level2">

<h3 id="reflexion-three-model-architecture">Reflexion: Three-Model Architecture</h3>
<div style="font-size: 80%;">
<p>Reflexion is composed of three distinct LLM-based models:</p>
<pre><code>                Environment
                    │  Obs / Reward
                    ▼
┌─────────────────────────────────────────┐
│                  Agent                  │
│  ┌──────────┐    ┌──────────────────┐   │
│  │  Actor   │◄───│ Long-term Memory │   │
│  │  (M_a)   │    │     (mem)        │   │
│  └────┬─────┘    └────────▲─────────┘   │
│       │ trajectory τ      │ sr_t        │
│  ┌────▼─────┐    ┌────────┴─────────┐   │
│  │Evaluator │    │  Self-Reflection │   │
│  │  (M_e)   │───►│     (M_sr)       │   │
│  └──────────┘    └──────────────────┘   │
└─────────────────────────────────────────┘
                    │  Action a_t
                    ▼
                Environment</code></pre>
</div>
</section>
<section class="slide level2">

<h3 id="reflexion-three-model-architecture-1">Reflexion: Three-Model Architecture</h3>
<div style="font-size: 75%;">
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 33%">
<col style="width: 38%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Symbol</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Actor</td>
<td><span class="math inline">\(M_a\)</span></td>
<td>Generates text and actions from state observations</td>
</tr>
<tr class="even">
<td>Evaluator</td>
<td><span class="math inline">\(M_e\)</span></td>
<td>Scores the Actor’s trajectory; produces reward <span class="math inline">\(r_t\)</span></td>
</tr>
<tr class="odd">
<td>Self-Reflection</td>
<td><span class="math inline">\(M_{sr}\)</span></td>
<td>Converts sparse reward into verbal feedback <span class="math inline">\(sr_t\)</span></td>
</tr>
</tbody>
</table>
</div>
</section>
<section class="slide level2">

<h3 id="memory-short-term-vs-long-term">Memory : Short-Term vs Long-Term</h3>
<div style="font-size: 55%;">
<p><strong>Short-Term Memory (trajectory):</strong></p>
<ul>
<li>Current trial’s trajectory history</li>
<li>Contains: <span class="math inline">\(\tau_t = [a_0, o_0, a_1, o_1, \ldots, a_n, o_n]\)</span></li>
<li>Actions <span class="math inline">\(a_i\)</span> and observations <span class="math inline">\(o_i\)</span> from the ongoing episode</li>
<li>Resets at the start of each new trial</li>
<li>Kept in the LLM’s active context window</li>
</ul>
<p><strong>Long-Term Memory (<code>mem</code>):</strong></p>
<ul>
<li>Accumulated self-reflection outputs <span class="math inline">\(\{sr_0, sr_1, \ldots\}\)</span></li>
<li>Persists across trials as a <strong>sliding window</strong></li>
<li>Bounded by <span class="math inline">\(\Omega = 1\text{–}3\)</span> most recent reflections (to fit context)</li>
<li>Provides “self-hints” for the next episode</li>
<li>Key advantage over other LLM agent approaches</li>
</ul>
<blockquote>
<p>Memory is capped at <span class="math inline">\(\Omega\)</span> experiences to avoid exceeding LLM context window limits.</p>
</blockquote>
</div>
</section>
<section class="slide level2">

<h3 id="the-reflexion-algorithm">The Reflexion Algorithm</h3>
<div style="font-size: 50%;">
<p><strong>Short-Term Memory (trajectory):</strong></p>
<ul>
<li><p>Initialise Actor, Evaluator, Self-Reflection: <span class="math inline">\(M_a, M_e, M_sr\)</span></p></li>
<li><p>Initialise policy <span class="math inline">\(π_θ(a_t | s_t),  θ = {M_a, mem}\)</span></p></li>
<li><p>Generate initial trajectory <span class="math inline">\(τ₀\)</span> using <span class="math inline">\(π_θ\)</span></p></li>
<li><p>Evaluate <span class="math inline">\(τ₀\)</span>: <span class="math inline">\(r₀ = M_e(τ₀)\)</span></p></li>
<li><p>Self-reflect: <span class="math inline">\(sr₀ = M_sr(τ₀, r₀)\)</span></p></li>
<li><p>Set mem ← <span class="math inline">\([sr₀]\)</span></p></li>
<li><p>Set t = 0</p></li>
</ul>
<p>──────────────────────────────────────────────</p>
<p>while <span class="math inline">\(M_e(τ)\)</span> ≠ pass OR <span class="math inline">\(t\)</span> &lt; max_trials:</p>
<ul>
<li><p>Generate <span class="math inline">\(τ_t\)</span> = <span class="math inline">\([a₀, o₀, … a_i, o_i]\)</span> using <span class="math inline">\(π_θ\)</span></p></li>
<li><p>Evaluate: <span class="math inline">\(r_t  = M_e(τ_t)\)</span></p></li>
<li><p>Self-reflect: <span class="math inline">\(sr_t = M_sr(τ_t, r_t, mem)\)</span></p></li>
<li><p>Append <span class="math inline">\(sr_t\)</span> to mem</p></li>
<li><p>Increment <span class="math inline">\(t\)</span></p></li>
</ul>
<p>──────────────────────────────────────────────</p>
<p>return</p>
</div>
</section>
<section class="slide level2">

<h3 id="the-reflexion-algorithm-1">The Reflexion Algorithm</h3>
<div style="font-size: 75%;">
<p><strong>Key Steps:</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 17%">
<col style="width: 37%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Step</th>
<th>What happens</th>
<th>Why it matters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(r_t = M_e(τ_t)\)</span></td>
<td>Evaluator scores trajectory</td>
<td>Provides binary/scalar feedback signal</td>
</tr>
<tr class="even">
<td><span class="math inline">\(sr_t = M_sr(τ_t, r_t, mem)\)</span></td>
<td>Self-Reflection generates verbal summary</td>
<td>Converts sparse reward → rich actionable text</td>
</tr>
<tr class="odd">
<td><code>mem</code> ← append <span class="math inline">\(sr_t\)</span></td>
<td>Memory updated</td>
<td>Carries learning across episodes</td>
</tr>
<tr class="even">
<td>No weight update</td>
<td>LLM params frozen</td>
<td>Enables lightweight deployment</td>
</tr>
</tbody>
</table>
</div>
</section>
<section class="slide level2">

<h3 id="evaluator-design">Evaluator Design</h3>
<div style="font-size: 60%;">
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 18%">
<col style="width: 26%">
<col style="width: 24%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Type</th>
<th>Example</th>
<th>✓ Advantage</th>
<th>✗ Drawback</th>
<th>Used for</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Binary environment reward</td>
<td>AlfWorld: task complete? Yes/No</td>
<td>Simple, no extra model</td>
<td>Sparse, no direction</td>
<td>Decision-making</td>
</tr>
<tr class="even">
<td>Heuristic / rule-based</td>
<td>Same action ×3 = stuck → reflect</td>
<td>Fast, domain-specific</td>
<td>Requires manual design</td>
<td>Decision-making</td>
</tr>
<tr class="odd">
<td>LLM self-evaluation</td>
<td>CoT grading of generated answers</td>
<td>No ground-truth labels needed</td>
<td>Depends on LLM capability</td>
<td>Reasoning</td>
</tr>
<tr class="even">
<td>Self-generated unit tests</td>
<td>CoT test suite executed by compiler</td>
<td>Grounded via actual execution</td>
<td>Flaky tests → false positives</td>
<td>Programming</td>
</tr>
</tbody>
</table>
</div>
</section>
<section class="slide level2">

<h3 id="experiments">Experiments</h3>
<section id="decision-making-alfworld-setup" style="font-size: 50%;">
<h3>Decision-Making — AlfWorld Setup</h3>
<p><strong>Environment:</strong> AlfWorld — text-based household tasks built on TextWorld.</p>
<p><strong>134 environments across 6 task types:</strong></p>
<ul>
<li>Find hidden objects (e.g., spatula in a drawer)</li>
<li>Move objects to target locations</li>
<li>Manipulate objects with other objects</li>
<li>Examine items under a light source</li>
</ul>
<p><strong>Agent configuration:</strong></p>
<ul>
<li>Actor: <strong>ReAct</strong> (reasoning + action generation)</li>
<li>Evaluator: LLM-based binary classification <strong>OR</strong> hand-written heuristic</li>
<li>Heuristic rule: same action repeated ≥ 3 times, OR &gt; 30 steps taken → trigger reflection</li>
<li>Memory: last <span class="math inline">\(\Omega = 3\)</span> self-reflections</li>
</ul>
<p><strong>Two failure modes Reflexion learns to fix:</strong></p>
<ol type="1">
<li><strong>Hallucination</strong> — agent thinks it has an item it doesn’t possess</li>
<li><strong>Inefficient planning</strong> — agent circles through same locations repeatedly</li>
</ol>
</section>
</section>
<section class="slide level2">

<h3 id="experiments-1">Experiments</h3>
<section id="decision-making-alfworld-results" style="font-size: 50%;">
<h3>Decision-Making — AlfWorld Results</h3>
<table class="caption-top">
<thead>
<tr class="header">
<th>Trial</th>
<th>ReAct Only</th>
<th>Reflexion (Heuristic)</th>
<th>Reflexion (GPT)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0.54</td>
<td>0.54</td>
<td>0.54</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.63</td>
<td>0.75</td>
<td>0.73</td>
</tr>
<tr class="odd">
<td>4</td>
<td>0.67</td>
<td>0.83</td>
<td>0.81</td>
</tr>
<tr class="even">
<td>6</td>
<td>0.69</td>
<td>0.90</td>
<td>0.88</td>
</tr>
<tr class="odd">
<td>8</td>
<td>0.70</td>
<td>0.94</td>
<td>0.92</td>
</tr>
<tr class="even">
<td>10</td>
<td>0.70</td>
<td>0.96</td>
<td>0.94</td>
</tr>
<tr class="odd">
<td>12</td>
<td>0.70</td>
<td><strong>0.97</strong></td>
<td>0.95</td>
</tr>
</tbody>
</table>
<p><strong>Key findings:</strong></p>
<ul>
<li>ReAct + Reflexion solves <strong>130/134 tasks</strong> (vs ~94 for ReAct alone)</li>
<li>ReAct-only improvement <strong>stalls between trials 6–7</strong></li>
<li>ReAct-only converges at ~<strong>22% hallucination rate</strong> with no recovery</li>
<li>Reflexion nearly eliminates hallucination errors within 12 trials</li>
</ul>
</section>
</section>
<section class="slide level2">

<h3 id="experiments-2">Experiments</h3>
<section id="reasoning-hotpot-qa" style="font-size: 50%;">
<h3>Reasoning — HotPot QA</h3>
<p><strong>Dataset:</strong> HotPotQA — 113,000 Wikipedia-based multi-hop Q&amp;A pairs</p>
<p><strong>Three agent variants tested:</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 19%">
<col style="width: 30%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Variant</th>
<th>Input</th>
<th>Prompting</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CoT (Q→A)</td>
<td>Question only</td>
<td>6-shot</td>
<td>Tests reasoning without retrieval</td>
</tr>
<tr class="even">
<td>CoT-GT (Q, C_gt → A)</td>
<td>Question + ground-truth context</td>
<td>6-shot</td>
<td>Tests pure reasoning quality</td>
</tr>
<tr class="odd">
<td>ReAct</td>
<td>Question + Wikipedia API</td>
<td>2-shot</td>
<td>Tests holistic Q&amp;A ability</td>
</tr>
</tbody>
</table>
<p><strong>Evaluation:</strong> Exact match (EM) grading → binary success signal</p>
<p><strong>Memory:</strong> <span class="math inline">\(\Omega = 3\)</span> experiences per task</p>
<blockquote>
<p><strong>Critical finding:</strong> Without Reflexion, ALL baseline approaches (ReAct, CoT, CoT-GT) fail to probabilistically improve across retries at temperature 0.7. Failed tasks stay failed across all subsequent trials.</p>
</blockquote>
</section>
</section>
<section class="slide level2">

<h3 id="experiments-3">Experiments</h3>
<section id="reasoning-hotpot-qa-results" style="font-size: 50%;">
<h3>Reasoning — HotPot QA Results</h3>
<table class="caption-top">
<thead>
<tr class="header">
<th>Approach</th>
<th>Trial 0</th>
<th>Trial 3</th>
<th>Trial 5</th>
<th>Improvement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CoT only</td>
<td>0.26</td>
<td>0.26</td>
<td>0.26</td>
<td>0%</td>
</tr>
<tr class="even">
<td>ReAct only</td>
<td>0.30</td>
<td>0.30</td>
<td>0.30</td>
<td>0%</td>
</tr>
<tr class="odd">
<td>CoT + Reflexion</td>
<td>0.26</td>
<td>0.40</td>
<td>0.44</td>
<td>+18pp</td>
</tr>
<tr class="even">
<td>ReAct + Reflexion</td>
<td>0.30</td>
<td>0.49</td>
<td><strong>0.52</strong></td>
<td><strong>+22pp</strong></td>
</tr>
<tr class="odd">
<td>CoT-GT only</td>
<td>0.61</td>
<td>0.61</td>
<td>0.61</td>
<td>0%</td>
</tr>
<tr class="even">
<td>CoT-GT + Reflexion</td>
<td>0.61</td>
<td>0.78</td>
<td><strong>0.80</strong></td>
<td><strong>+19pp</strong></td>
</tr>
</tbody>
</table>
<p><strong>Ablation result:</strong></p>
<ul>
<li>Episodic memory alone (EPM): <strong>+~14%</strong> over baseline</li>
<li>Self-reflection on top of EPM: <strong>+8% additional</strong></li>
<li>Total Reflexion advantage over raw trajectory replay: <strong>+8pp</strong></li>
</ul>
</section>
</section>
<section class="slide level2">

<h3 id="experiments-4">Experiments</h3>
<section id="programming-task-setup" style="font-size: 50%;">
<h3>Programming — Task Setup</h3>
<p><strong>Benchmarks:</strong></p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 28%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Benchmark</th>
<th>Language</th>
<th>Problems</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HumanEval</td>
<td>Python, Rust</td>
<td>164 (PY), 50 hardest (RS)</td>
<td>Function body generation; pass@1</td>
</tr>
<tr class="even">
<td>MBPP</td>
<td>Python, Rust</td>
<td>~374</td>
<td>Mostly Basic Programming Problems</td>
</tr>
<tr class="odd">
<td>LeetcodeHardGym</td>
<td>Python</td>
<td>40</td>
<td>Released AFTER GPT-4 training cutoff (Oct 8 2022)</td>
</tr>
</tbody>
</table>
<p><strong>Unit test generation pipeline:</strong></p>
<pre><code>1. CoT prompting → diverse test suite with natural language descriptions
2. Filter: keep only tests with valid Abstract Syntax Tree (AST)
3. Sample n ≤ 6 tests → T = {t₀, t₁, …, tₙ}
4. Execute against generated code → pass/fail → feeds self-reflection
</code></pre>
<p>Unit Test provide <strong>grounded, execution-verified</strong> feedback — stronger than LLM self-evaluation alone, and eligible for pass@1 accuracy reporting.</p>
</section>
</section>
<section class="slide level2">

<h3 id="experiments-5">Experiments</h3>
<section id="programming-results" style="font-size: 50%;">
<h3>Programming — Results</h3>
<table class="caption-top">
<colgroup>
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 17%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Benchmark + Language</th>
<th>Previous SOTA pass@1</th>
<th>GPT-4 pass@1</th>
<th><strong>Reflexion pass@1</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HumanEval (Python)</td>
<td>65.8 (CodeT + GPT-3.5)</td>
<td>80.1</td>
<td><strong>91.0</strong> ▲10.9pp</td>
</tr>
<tr class="even">
<td>HumanEval (Rust)</td>
<td>—</td>
<td>60.0</td>
<td><strong>68.0</strong> ▲8pp</td>
</tr>
<tr class="odd">
<td>MBPP (Python)</td>
<td>67.7 (CodeT + Codex)</td>
<td><strong>80.1</strong></td>
<td>77.1 ▼ (see analysis)</td>
</tr>
<tr class="even">
<td>MBPP (Rust)</td>
<td>—</td>
<td>70.9</td>
<td><strong>75.4</strong> ▲4.5pp</td>
</tr>
<tr class="odd">
<td>Leetcode Hard (Python)</td>
<td>—</td>
<td>7.5</td>
<td><strong>15.0</strong> ▲7.5pp (×2)</td>
</tr>
</tbody>
</table>
<p><strong>Why did MBPP Python underperform?</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Benchmark</th>
<th>False Positive Rate</th>
<th>Reflexion pass@1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HumanEval PY</td>
<td><strong>1.4%</strong></td>
<td>91.0%</td>
</tr>
<tr class="even">
<td>MBPP PY</td>
<td><strong>16.3%</strong></td>
<td>77.1%</td>
</tr>
</tbody>
</table>
<p>False positive = tests pass on <em>incorrect</em> code → agent prematurely accepts wrong solution.</p>
<p><span class="math display">\[
P(\text{fail} \mid \text{tests pass}) = 16.3\% \text{ for MBPP vs } 1.4\% \text{ for HumanEval}
\]</span></p>
</section>
</section>
<section class="slide level2">

<h3 id="experiments-6">Experiments</h3>
<section id="worked-example-alfworld-trial-reflection" style="font-size: 50%;">
<h3>Worked Example — AlfWorld Trial &amp; Reflection</h3>
<p><strong>Task:</strong> Examine the mug with the desklamp.</p>
<p><strong>Trial #1 — FAIL:</strong></p>
<pre><code>Think: find mug first, then find desklamp
→ go to drawer 1..6 (mug not found)
→ go to desk 1: find mug 1, take it ✓
→ go to desk 2 looking for desklamp
→ use desklamp 1: Nothing happens ✗
→ use desklamp 1: Nothing happens ✗
 
Status: FAIL</code></pre>
<p><strong>Self-Reflection generated by <span class="math inline">\(M_{sr}\)</span>:</strong></p>
<blockquote>
<p><em>“I tried to find the mug before the desklamp. I should have looked for the desklamp first — I noticed it was on desk 1. Next trial: go to desk 1, pick up the lamp, then find and examine the mug with it.”</em></p>
</blockquote>
<p><strong>Trial #2 — SUCCESS:</strong></p>
<pre><code>[mem loaded: look for desklamp first]
→ go to desk 1
→ sees desklamp 1 AND mug 1 (both here!)
→ take mug 1 from desk 1
→ use desklamp 1: "You turn on the desklamp" ✓
 
Status: SUCCESS  (3 actions vs 10+ failed attempt)</code></pre>
</section>
</section>
<section class="slide level2">

<h3 id="ablation-studies">Ablation Studies</h3>
<section id="code-generation-what-drives-the-gains-humaneval-rust-50-hardest" style="font-size: 50%;">
<h3>Code Generation — What Drives the Gains? (HumanEval Rust, 50 hardest)</h3>
<table class="caption-top">
<thead>
<tr class="header">
<th>Variant</th>
<th>pass@1</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Base model</td>
<td>0.60</td>
<td>Single generation, no Reflexion</td>
</tr>
<tr class="even">
<td>No test generation</td>
<td><strong>0.52</strong></td>
<td>Reflection only, no unit tests</td>
</tr>
<tr class="odd">
<td>No self-reflection</td>
<td>0.60</td>
<td>Tests only, no verbal explanation</td>
</tr>
<tr class="even">
<td><strong>Full Reflexion</strong></td>
<td><strong>0.68</strong></td>
<td>Tests + self-reflection</td>
</tr>
</tbody>
</table>
<p><strong>Analysis of each omission:</strong></p>
<ul>
<li><p><strong>No test generation → 0.52 (worse than baseline)</strong><br>
Without unit tests the agent cannot assess whether its code is correct. It must participate in all iterations — even successful ones — causing harmful edits to working code.</p></li>
<li><p><strong>No self-reflection → 0.60 (same as baseline)</strong><br>
Tests catch syntax and logic errors, but without the verbal explanation step, the agent cannot translate the error signal into an implementation fix. The two components are <strong>synergistic</strong>.</p></li>
<li><p><strong>Full Reflexion → 0.68</strong><br>
Tests answer <em>what</em> is wrong. Self-reflection synthesises <em>why</em> and proposes a fix.</p></li>
</ul>
<blockquote>
<p>Tests alone ≠ improvement. Reflection alone &lt; baseline. <strong>Both together = new SOTA.</strong></p>
</blockquote>
</section>
</section>
<section class="slide level2">

<h3 id="ablation-studies-1">Ablation Studies</h3>
<section id="reasoning-ablation-episodic-memory-vs-reflexion-hotpotqa-cot-gt" style="font-size: 60%;">
<h3>Reasoning Ablation — Episodic Memory vs Reflexion (HotPotQA CoT-GT)</h3>
<table class="caption-top">
<thead>
<tr class="header">
<th>Approach</th>
<th>Trial 0</th>
<th>Trial 2</th>
<th>Trial 4</th>
<th>Δ vs baseline</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CoT-GT only</td>
<td>0.61</td>
<td>0.61</td>
<td>0.61</td>
<td>—</td>
</tr>
<tr class="even">
<td>CoT-GT + EPM</td>
<td>0.61</td>
<td>0.72</td>
<td>0.75</td>
<td>+14pp</td>
</tr>
<tr class="odd">
<td>CoT-GT + EPM + Reflexion</td>
<td>0.61</td>
<td>0.78</td>
<td><strong>0.83</strong></td>
<td><strong>+22pp</strong></td>
</tr>
</tbody>
</table>
<ul>
<li><strong>EPM (Episodic Memory):</strong> append the most recent full trajectory to context.<br>
</li>
<li><strong>Reflexion:</strong> replace the raw trajectory with a <em>first-person verbal self-reflection</em>.</li>
</ul>
<p><span class="math display">\[
\Delta_{\text{Reflexion over EPM}} = +8\text{pp absolute accuracy}
\]</span></p>
<p>This supports the argument that <strong>refinement-only approaches</strong> (re-reading the raw trajectory) are not as effective as <strong>self-reflection-guided refinement</strong> (reading a distilled verbal lesson).</p>
</section>
</section>
<section class="slide level2">

<h3 id="ablation-studies-2">Ablation Studies</h3>
<section id="where-reflexion-breaks-down-webshop" style="font-size: 50%;">
<h3>Where Reflexion Breaks Down — WebShop</h3>
<p><strong>WebShop:</strong> E-commerce navigation — find and purchase products from natural language descriptions.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Trial</th>
<th>ReAct Only</th>
<th>ReAct + Reflexion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0.33</td>
<td>0.35</td>
</tr>
<tr class="even">
<td>1</td>
<td>0.33</td>
<td>0.35</td>
</tr>
<tr class="odd">
<td>2</td>
<td>0.33</td>
<td>0.36</td>
</tr>
<tr class="even">
<td>3</td>
<td>0.33</td>
<td>0.36</td>
</tr>
</tbody>
</table>
<p><em>Experiment terminated after 4 trials — no meaningful improvement.</em></p>
</section>
</section>
<section class="slide level2">

<h3 id="ablation-studies-3">Ablation Studies</h3>
<section id="where-reflexion-breaks-down-webshop-1" style="font-size: 50%;">
<h3>Where Reflexion Breaks Down — WebShop</h3>
<p><strong>Why does Reflexion fail here?</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 38%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>Reason</th>
<th>Explanation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Local minima</td>
<td>Reflexion optimises from its current trajectory; cannot escape a bad search strategy</td>
</tr>
<tr class="even">
<td>Needs diversity</td>
<td>WebShop requires very creative, unique search queries — Reflexion produces repetitive reflections</td>
</tr>
<tr class="odd">
<td>Ambiguous space</td>
<td>E-commerce NL search is highly ambiguous; Reflexion cannot bridge failed query semantics</td>
</tr>
<tr class="even">
<td>Contrast: AlfWorld</td>
<td>AlfWorld succeeds because permissible actions are enumerable in observations; WebShop is unbounded</td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>Key limitation:</strong> Reflexion is a local optimiser. Tasks that require <em>radical exploration</em> or <em>very high action space diversity</em> are out of its reach.</p>
</blockquote>
</section>
</section>
<section class="slide level2">

<h3 id="limitations">Limitations</h3>
<div style="font-size: 50%;">
<table class="caption-top">
<colgroup>
<col style="width: 57%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Limitation</th>
<th>Detail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Local minima</td>
<td>Verbal RL converges to locally-optimal solutions; no global optimality guarantee</td>
</tr>
<tr class="even">
<td>LLM quality ceiling</td>
<td>Self-correction is an emergent property of <strong>strong models only</strong> — starchat-beta shows zero improvement</td>
</tr>
<tr class="odd">
<td>Context window cap</td>
<td>Memory bounded by <span class="math inline">\(\Omega\)</span>; future work: vector DB or SQL-backed external memory</td>
</tr>
<tr class="even">
<td>Flaky test suite</td>
<td>Programming tasks depend on self-generated tests; flaky tests mislead the agent</td>
</tr>
<tr class="odd">
<td>No formal convergence</td>
<td>Unlike classical RL, no proof that Reflexion terminates within finite trials</td>
</tr>
<tr class="even">
<td>Safety / misuse risk</td>
<td>Greater autonomy = greater risk; self-reflections need monitoring before tool use</td>
</tr>
</tbody>
</table>
<p><strong>Starchat-beta ablation (shows LLM quality dependency):</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Approach</th>
<th>pass@1 (avg over 8 trials)</th>
<th>pass@1 (std)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Baseline</td>
<td>0.26</td>
<td>0.00481</td>
</tr>
<tr class="even">
<td>Reflexion</td>
<td>0.26</td>
<td>0.00305</td>
</tr>
</tbody>
</table>
<p><em>Zero improvement — self-reflection is an emergent quality of stronger, larger models.</em></p>
</div>
</section>
<section class="slide level2">

<h3 id="impact-and-future-directions">Impact and Future Directions</h3>
<div style="font-size: 50%;">
<p><strong>Interpretability advantage:</strong></p>
<ul>
<li>Unlike black-box RL, Reflexion’s self-reflections are human-readable</li>
<li>Monitoring text reflections <em>before</em> executing tools → alignment potential</li>
<li>Conversation logs become an auditable learning trail</li>
<li><strong>Misuse risk:</strong> : Greater agent capability amplifies misuse risk</li>
<li>Autonomous code execution must run in <strong>isolated sandboxes</strong></li>
<li>Safety &amp; ethics research must co-evolve with capabilities</li>
</ul>
<p><strong>Future directions:</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 45%">
<col style="width: 54%">
</colgroup>
<thead>
<tr class="header">
<th>Direction</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Vector / SQL memory</td>
<td>Replace sliding window with scalable external memory for unbounded learning</td>
</tr>
<tr class="even">
<td>Off-policy exploration</td>
<td>Apply ε-greedy or UCB techniques during verbal RL trial selection</td>
</tr>
<tr class="odd">
<td>Value learning in language</td>
<td>Learn NL value functions to estimate expected future success per stage</td>
</tr>
<tr class="even">
<td>Formal verification</td>
<td>Use theorem provers / formal specs to ground code evaluation beyond unit tests</td>
</tr>
</tbody>
</table>
</div>
</section>
<section class="slide level2">

<h3 id="key-takeaways">Key Takeaways</h3>
<div style="font-size: 50%;">
<ol type="1">
<li><p><strong>Verbal Reinforcement is Real</strong> — LLMs can learn within a few trials using natural language alone; no gradient descent required.</p></li>
<li><p><strong>Memory is the Key Ingredient</strong> — Self-reflections stored in episodic memory provide +8% accuracy over raw trajectory replay alone.</p></li>
<li><p><strong>Tests + Reflection are Synergistic</strong> — For code generation, neither unit tests alone nor reflection alone achieves gains; both are required.</p></li>
<li><p><strong>New SOTA on Code Benchmarks</strong> — 91% HumanEval Python pass@1, surpassing GPT-4 (80.1%); doubles GPT-4’s Leetcode Hard rate to 15%.</p></li>
<li><p><strong>Still Has Limits</strong> — Local minima, LLM capability ceiling, context window size, and flaky tests all constrain Reflexion’s applicability.</p></li>
</ol>
</div>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/PC_White.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://arxiv.org/pdf/2303.11366">Reflexion: Language Agents with Verbal Reinforcement Learning (2023)</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>